spring:
  profiles:
    active: dev
---
spring:
  profiles: dev

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/realestate_data?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: kim111
    driver-class-name: com.mysql.jdbc.Driver

  main:
    web-application-type: none

---
spring:
  profiles: test

  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/spring_batch_test?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: kim111
    driver-class-name: com.mysql.jdbc.Driver

  main:
    web-application-type: none