spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch?useSSL=false&serverTimezone=Asia/Seoul
      username: root
      password: kim111
      driver-class-name: com.mysql.jdbc.Driver

  main:
    web-application-type: none